---
title: "Raw_readcounts"
author: "Guannan Shen"
date: "July 12, 2018"
output: 
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 5
    toc_float: yes
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 5
  word_document:
    toc: yes
    toc_depth: '5'
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
knitr::opts_chunk$set(engine = "R")
getwd()                                          ## get the path work directory
                                                 ## cache = F, if cache = T, will not revaluate code chunk everytime
## double or more space to insert a line break
```

# Raw read counts

```{r raw read counts table, echo=FALSE,warning=FALSE}
#####################################
# Raw read counts
#####################################

options(stringsAsFactors=FALSE)
library(knitr)
library(kableExtra)
library(pander)

## or using setwd('') to set the wd as whatever you want 
## such as setwd("D:/01_CIDA/Training/my1stproj")
projectFolder <- paste(getwd(), "/", sep = '')
rawCounts = read.table(file=paste(projectFolder,"countSummary.txt",sep=""),sep=" ",header=FALSE,fill=TRUE)

rawCounts$readFrag = as.numeric(rawCounts$V3)
rawCounts$file = sapply(strsplit(rawCounts$V1,split="/",fixed=TRUE),function(a) a[length(a)])
rawCounts$sample = sapply(strsplit(rawCounts$file,split="_",fixed=TRUE),function(a) paste(a[1], "_", a[2], sep = ""))
rawCounts$sample = sapply(strsplit(rawCounts$file,split=".",fixed=TRUE),function(a) a[1])

## aggregate by sample and get the sum of rawCounts 
readFragments = aggregate(rawCounts$readFrag,by=list(sample=rawCounts$sample),sum)
#forCSV <- forPrint
#forCSV$`Number of Read Fragments` <- readFragments$x
#write.csv(forCSV, file = "/Volumes/smiharry/CBC/P1218Fontenot/data/rawReadCounts-P1218Fontenot.csv", row.names = FALSE, quote = FALSE)
#readFragments$numPairedReads = prettyNum(readFragments$x/2,big.mark=",",scientific=FALSE)
readFragments$numReadFragments = prettyNum(readFragments$x,big.mark=",",scientific=FALSE)

readFragments=readFragments[,colnames(readFragments)!="x"]
forPrint = readFragments[,c("sample","numReadFragments")]
colnames(forPrint) = c("sample","Number of Read Fragments")

kable(forPrint,align=rep("c",ncol(readFragments)), caption = "")

#####################################
#Trimmed read counts
#####################################

trimmed = read.table(file=paste(projectFolder,"trimmedSummary.txt",sep=""),sep="",header=FALSE)
trimmed$file = unlist(lapply(strsplit(trimmed$V1,split="/",fixed=TRUE),function(a) a[length(a)]))
trimmed$sample = unlist(lapply(strsplit(trimmed$file,split="_",fixed=TRUE),function(a) paste(a[1], "_", a[2], sep = "")))
trimmed$read = unlist(lapply(strsplit(trimmed$file,split="_",fixed=TRUE),function(a) a[3])) 
trimmed$read = unlist(lapply(strsplit(trimmed$read,split=".",fixed=TRUE),function(a) a[1])) 
#trimmed$lane = unlist(lapply(strsplit(trimmed$file,split="_",fixed=TRUE),function(a) a[5])) #We used the concatenated files so there is no lane information

bySample = trimmed[trimmed$read=="R1",c("sample","V2","V3")]
bySample$numReadFrag = bySample$V3
colnames(bySample) = c("sample","avgFragLength","numReads","numReadFrag")

bySample = merge(readFragments,bySample,by=c("sample"))
bySample$pctReadsAfterTrim = paste(sprintf("%.1f",round(100*bySample$numReads/as.numeric(gsub(",","",bySample$numReadFragments)),1)),"%",sep="")

forPrint2 = bySample[,c("sample","numReadFragments","avgFragLength", "numReadFrag","pctReadsAfterTrim")]
forPrint2$avgFragLength = sprintf("%.1f",round(forPrint2$avgFragLength,1))
forPrint2$numReadFrag = prettyNum(forPrint2$numReadFrag,big.mark=",")

colnames(forPrint2) = c("sample","Number of Read Fragments","Average Read Fragment Length After Trimming","Number of Read Fragments After Trimming","Percent of Read Fragments That Remained After Trimming")

#kable(forPrint2,align=rep("c",ncol(forPrint2))) 
#forCSV2 <- forPrint2
#forCSV2$`Number of Read Fragments` <- as.numeric(gsub(",","",bySample$numReadFragments))
#forCSV2$`Number of Read Fragments After Trimming` <- bySample$numReads
#write.csv(forCSV2, file = "/Volumes/smiharry/CBC/P1218Fontenot/data/trimmedReadCounts-P1218Fontenot.csv", row.names = FALSE, quote = FALSE)

kable(forPrint2)

```




